'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("cfCbBusJS.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to // [baseJoin56],[baseJoin202],[bPercent]
        '''// version 1.0
        '''// ***SCRIPT STARTS HERE***
        '''/*======================================================================\
        '''|               CommandFusion CBus Control JS Script                    |
        '''|-----------------------------------------------------------------------|
        '''| WARNING! Any changes made to this script WILL be overwritten whenever |
        '''| new commands are generated.                                           |
        '''\================================================= [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property cbus() As String
            Get
                Return ResourceManager.GetString("cbus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        '''&lt;html&gt;&lt;body&gt;&lt;font face=&apos;arial&apos; size=&apos;2&apos;&gt;
        '''&lt;ul&gt;
        '''    &lt;li&gt;
        '''        Create a &lt;b&gt;slider&lt;/b&gt; object, and assign it an analog join equal to the configured base join + the &lt;i&gt;decimal&lt;/i&gt; 
        '''        C-Bus group ID. eg. If you configured a base join of 1000, and you&apos;re wanting to control group 15, you&apos;d use 
        '''        join 1015.
        '''    &lt;/li&gt;
        '''    &lt;li&gt;
        '''        Assign the appropriate command to the &lt;b&gt;release&lt;/b&gt; parameter of the slider (if you drag and dro [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property help_slider() As String
            Get
                Return ResourceManager.GetString("help_slider", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        '''&lt;html&gt;&lt;body&gt;&lt;font face=&apos;arial&apos; size=&apos;2&apos;&gt;
        '''&lt;ul&gt;
        '''    &lt;li&gt;
        '''        Create a &lt;b&gt;slider&lt;/b&gt; object, and assign it an analog join equal to the configured base join + the &lt;i&gt;decimal&lt;/i&gt; 
        '''        C-Bus group ID. eg. If you configured a base join of 1000, and you&apos;re wanting to control group 15, you&apos;d use 
        '''        join 1015.
        '''    &lt;/li&gt;
        '''    &lt;li&gt;
        '''        Assign the appropriate command to the &lt;b&gt;release&lt;/b&gt; parameter of the slider (if you drag and dro [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property help_toggle() As String
            Get
                Return ResourceManager.GetString("help_toggle", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
